import { Tile, GameConfig } from '../engine/types';

export const BOARD_TILES: Tile[] = [
  { position: 0, name: 'Los', type: 'go' },
  {
    position: 1,
    name: 'Biebricher Allee',
    type: 'property',
    color: 'brown',
    price: 40,
    housePrice: 30,
    rent: [2, 10, 30, 90, 160, 250],
    houses: 0,
    mortgaged: false,
  },
  { position: 2, name: 'Gemeinschaftskarte', type: 'community_chest' },
  {
    position: 3,
    name: 'Schiersteiner Straße',
    type: 'property',
    color: 'brown',
    price: 60,
    housePrice: 30,
    rent: [4, 20, 60, 180, 320, 450],
    houses: 0,
    mortgaged: false,
  },
  { position: 4, name: 'Einkommensteuer', type: 'tax', amount: 80 },
  { position: 5, name: 'Hauptbahnhof Wiesbaden', type: 'railroad', price: 130, mortgaged: false },
  {
    position: 6,
    name: 'Wilhelmstraße',
    type: 'property',
    color: 'lightblue',
    price: 70,
    housePrice: 40,
    rent: [5, 25, 75, 200, 370, 550],
    houses: 0,
    mortgaged: false,
  },
  { position: 7, name: 'Ereigniskarte', type: 'chance' },
  {
    position: 8,
    name: 'Luisenstraße',
    type: 'property',
    color: 'lightblue',
    price: 75,
    housePrice: 40,
    rent: [5, 25, 75, 210, 380, 560],
    houses: 0,
    mortgaged: false,
  },
  {
    position: 9,
    name: 'Rheinstraße',
    type: 'property',
    color: 'lightblue',
    price: 85,
    housePrice: 40,
    rent: [6, 30, 90, 250, 440, 650],
    houses: 0,
    mortgaged: false,
  },
  { position: 10, name: 'Gefängnisbesuch', type: 'jail' },
  {
    position: 11,
    name: 'Taunusstraße',
    type: 'property',
    color: 'pink',
    price: 95,
    housePrice: 50,
    rent: [7, 35, 100, 300, 550, 750],
    houses: 0,
    mortgaged: false,
  },
  { position: 12, name: 'Stadtwerke Wiesbaden', type: 'utility', price: 100, mortgaged: false },
  {
    position: 13,
    name: 'Sonnenberger Straße',
    type: 'property',
    color: 'pink',
    price: 100,
    housePrice: 50,
    rent: [7, 35, 100, 300, 550, 750],
    houses: 0,
    mortgaged: false,
  },
  {
    position: 14,
    name: 'Adolfsallee',
    type: 'property',
    color: 'pink',
    price: 110,
    housePrice: 50,
    rent: [8, 40, 110, 330, 600, 800],
    houses: 0,
    mortgaged: false,
  },
  { position: 15, name: 'Bahnhof Biebrich', type: 'railroad', price: 130, mortgaged: false },
  {
    position: 16,
    name: 'Marktstraße',
    type: 'property',
    color: 'orange',
    price: 120,
    housePrice: 60,
    rent: [9, 45, 125, 375, 700, 900],
    houses: 0,
    mortgaged: false,
  },
  { position: 17, name: 'Gemeinschaftskarte', type: 'community_chest' },
  {
    position: 18,
    name: 'Friedrichstraße',
    type: 'property',
    color: 'orange',
    price: 125,
    housePrice: 60,
    rent: [9, 45, 125, 375, 700, 900],
    houses: 0,
    mortgaged: false,
  },
  {
    position: 19,
    name: 'Kirchgasse',
    type: 'property',
    color: 'orange',
    price: 140,
    housePrice: 60,
    rent: [10, 50, 140, 420, 800, 1000],
    houses: 0,
    mortgaged: false,
  },
  { position: 20, name: 'Freiparken', type: 'free_parking' },
  {
    position: 21,
    name: 'Bleichstraße',
    type: 'property',
    color: 'red',
    price: 150,
    housePrice: 70,
    rent: [11, 55, 160, 480, 900, 1100],
    houses: 0,
    mortgaged: false,
  },
  { position: 22, name: 'Ereigniskarte', type: 'chance' },
  {
    position: 23,
    name: 'Goldgasse',
    type: 'property',
    color: 'red',
    price: 155,
    housePrice: 70,
    rent: [11, 55, 160, 480, 900, 1100],
    houses: 0,
    mortgaged: false,
  },
  {
    position: 24,
    name: 'Langgasse',
    type: 'property',
    color: 'red',
    price: 165,
    housePrice: 70,
    rent: [12, 60, 180, 540, 1000, 1200],
    houses: 0,
    mortgaged: false,
  },
  { position: 25, name: 'Bahnhof Klarenthal', type: 'railroad', price: 130, mortgaged: false },
  {
    position: 26,
    name: 'Kaiser-Friedrich-Ring',
    type: 'property',
    color: 'yellow',
    price: 175,
    housePrice: 80,
    rent: [13, 65, 190, 560, 1050, 1300],
    houses: 0,
    mortgaged: false,
  },
  {
    position: 27,
    name: 'Rheinufer',
    type: 'property',
    color: 'yellow',
    price: 180,
    housePrice: 80,
    rent: [13, 65, 190, 560, 1050, 1300],
    houses: 0,
    mortgaged: false,
  },
  { position: 28, name: 'Wiesbadener Therme', type: 'utility', price: 100, mortgaged: false },
  {
    position: 29,
    name: 'Dernsches Gelände',
    type: 'property',
    color: 'yellow',
    price: 190,
    housePrice: 80,
    rent: [14, 70, 200, 600, 1100, 1400],
    houses: 0,
    mortgaged: false,
  },
  { position: 30, name: 'Gehe ins Gefängnis', type: 'go_to_jail' },
  {
    position: 31,
    name: 'Nerotal',
    type: 'property',
    color: 'green',
    price: 200,
    housePrice: 100,
    rent: [16, 80, 220, 660, 1200, 1500],
    houses: 0,
    mortgaged: false,
  },
  {
    position: 32,
    name: 'Neroberg',
    type: 'property',
    color: 'green',
    price: 200,
    housePrice: 100,
    rent: [16, 80, 220, 660, 1200, 1500],
    houses: 0,
    mortgaged: false,
  },
  { position: 33, name: 'Gemeinschaftskarte', type: 'community_chest' },
  {
    position: 34,
    name: 'Reisinger-Anlagen',
    type: 'property',
    color: 'green',
    price: 220,
    housePrice: 100,
    rent: [18, 90, 250, 750, 1400, 1750],
    houses: 0,
    mortgaged: false,
  },
  { position: 35, name: 'Bahnhof Dotzheim', type: 'railroad', price: 130, mortgaged: false },
  { position: 36, name: 'Ereigniskarte', type: 'chance' },
  {
    position: 37,
    name: 'Kurhaus-Kolonnaden',
    type: 'property',
    color: 'darkblue',
    price: 240,
    housePrice: 120,
    rent: [22, 110, 330, 1000, 1800, 2000],
    houses: 0,
    mortgaged: false,
  },
  { position: 38, name: 'Luxussteuer', type: 'tax', amount: 50 },
  {
    position: 39,
    name: 'Schlossplatz',
    type: 'property',
    color: 'darkblue',
    price: 265,
    housePrice: 120,
    rent: [26, 130, 390, 1200, 2100, 2500],
    houses: 0,
    mortgaged: false,
  },
];

export const DEFAULT_CONFIG: GameConfig = {
  startMoney: 1000,
  winConditionNetWorth: 8000,
  goPassReward: 200,
  goLandReward: 400,
  jailBuyoutCost: 150,
  jailPosition: 10,
  goPosition: 0,
  freeParkingPosition: 20,
  goToJailPosition: 30,
  maxJailTurns: 3,
  auctionStartBid: 1,
  mortgageInterestRate: 0.1,
};

// Color group definitions
export const COLOR_GROUPS: Record<string, number[]> = {
  brown: [1, 3],
  lightblue: [6, 8, 9],
  pink: [11, 13, 14],
  orange: [16, 18, 19],
  red: [21, 23, 24],
  yellow: [26, 27, 29],
  green: [31, 32, 34],
  darkblue: [37, 39],
};

export const RAILROAD_POSITIONS = [5, 15, 25, 35];
export const UTILITY_POSITIONS = [12, 28];
